/* 
 * OpenBots Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = OpenBots.Service.API.Client.SwaggerDateConverter;

namespace OpenBots.Service.API.Model
{
    /// <summary>
    /// AgentSettingViewModel
    /// </summary>
    [DataContract]
    public partial class AgentSettingViewModel : IEquatable<AgentSettingViewModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentSettingViewModel" /> class.
        /// </summary>
        /// <param name="heartbeatInterval">heartbeatInterval.</param>
        /// <param name="jobLoggingInterval">jobLoggingInterval.</param>
        /// <param name="verifySslCertificate">verifySslCertificate.</param>
        public AgentSettingViewModel(int? heartbeatInterval = default(int?), int? jobLoggingInterval = default(int?), bool? verifySslCertificate = default(bool?))
        {
            this.HeartbeatInterval = heartbeatInterval;
            this.JobLoggingInterval = jobLoggingInterval;
            this.VerifySslCertificate = verifySslCertificate;
        }

        /// <summary>
        /// Gets or Sets HeartbeatInterval
        /// </summary>
        [DataMember(Name = "heartbeatInterval", EmitDefaultValue = false)]
        public int? HeartbeatInterval { get; set; }

        /// <summary>
        /// Gets or Sets JobLoggingInterval
        /// </summary>
        [DataMember(Name = "jobLoggingInterval", EmitDefaultValue = false)]
        public int? JobLoggingInterval { get; set; }

        /// <summary>
        /// Gets or Sets VerifySslCertificate
        /// </summary>
        [DataMember(Name = "verifySslCertificate", EmitDefaultValue = false)]
        public bool? VerifySslCertificate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AgentSettingViewModel {\n");
            sb.Append("  HeartbeatInterval: ").Append(HeartbeatInterval).Append("\n");
            sb.Append("  JobLoggingInterval: ").Append(JobLoggingInterval).Append("\n");
            sb.Append("  VerifySslCertificate: ").Append(VerifySslCertificate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AgentSettingViewModel);
        }

        /// <summary>
        /// Returns true if AgentSettingViewModel instances are equal
        /// </summary>
        /// <param name="input">Instance of AgentSettingViewModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AgentSettingViewModel input)
        {
            if (input == null)
                return false;

            return
                (
                    this.HeartbeatInterval == input.HeartbeatInterval ||
                    (this.HeartbeatInterval != null &&
                    this.HeartbeatInterval.Equals(input.HeartbeatInterval))
                ) &&
                (
                    this.JobLoggingInterval == input.JobLoggingInterval ||
                    (this.JobLoggingInterval != null &&
                    this.JobLoggingInterval.Equals(input.JobLoggingInterval))
                ) &&
                (
                    this.VerifySslCertificate == input.VerifySslCertificate ||
                    (this.VerifySslCertificate != null &&
                    this.VerifySslCertificate.Equals(input.VerifySslCertificate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HeartbeatInterval != null)
                    hashCode = hashCode * 59 + this.HeartbeatInterval.GetHashCode();
                if (this.JobLoggingInterval != null)
                    hashCode = hashCode * 59 + this.JobLoggingInterval.GetHashCode();
                if (this.VerifySslCertificate != null)
                    hashCode = hashCode * 59 + this.VerifySslCertificate.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
