/* 
 * OpenBots Server API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = OpenBots.Service.API.Client.SwaggerDateConverter;
using System.ComponentModel;

namespace OpenBots.Service.API.Model
{
    /// <summary>
    /// Defines JobStatusType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum JobStatusType
    {
        /// <summary>
        /// Enum Unknown for value: "Unknown"
        /// </summary>
        [EnumMember(Value = "0")]
        Unknown,
        /// <summary>
        /// Enum New for value: "New"
        /// </summary>
        [EnumMember(Value = "New")]
        New,
        /// <summary>
        /// Enum Assigned for value: "Assigned"
        /// </summary>
        [EnumMember(Value = "Assigned")]
        Assigned,
        /// <summary>
        /// Enum InProgress for value: "InProgress"
        /// </summary>
        [EnumMember(Value = "InProgress")]
        InProgress,
        /// <summary>
        /// Enum Failed for value: "Failed"
        /// </summary>
        [EnumMember(Value = "Failed")]
        Failed,
        /// <summary>
        /// Enum Completed for value: "Completed"
        /// </summary>
        [EnumMember(Value = "Completed")]
        Completed,
        /// <summary>
        /// Enum Abandoned for value: "Abandoned"
        /// </summary>
        [EnumMember(Value = "Abandoned")]
        Abandoned
    }
}
